#!/bin/bash

# usage: $0 ARCHIVES.gz

# get list of RPMs containing sysconfig teplate
zcat $1 | grep /var/adm/fillup-templates/sysconfig | sed -e 's#.*/\(.*/.*\)-[^-]*-[^-]*\.rpm: .*#\1.rpm#' | sort | uniq | while read x;
do
    # unpack templates from RPM
    echo Package: $x
    rpm2cpio /work/CDs/all/full-i386/suse/$x | cpio -ivd 'var/adm/fillup-templates/sysconfig*'
done

echo "--- Missing variables ---"


# check if variables are already present in meta_sys.config
ls -1 ./var/adm/fillup-templates | while read file;
do
    grep -v "^#" ./var/adm/fillup-templates/$file | grep -v "^$" | sed -e 's/\([^=]\)=.*/\1/' | while read var
    do
	grep $var meta_sys.config > /dev/null
	    if [ $? != 0 ]; then
		echo "$var	($file)"
	    fi
    done
done

